services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: demo-backend
    env_file:
      - ./backend/.env
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend/data:/app/data
    networks:
      - demo-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: demo-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "${FRONTEND_PORT}:8080"
    networks:
      - demo-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  demo-network:
    driver: bridge
